# Generated by Django 6.0 on 2025-12-26 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=100)),
                ('objective_weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('scorecard_year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_name', models.CharField(choices=[('Planned', 'Planned'), ('On Track', 'On Track'), ('Completed', 'Completed'), ('At Risk', 'At Risk'), ('Delayed', 'Delayed')], default='Not Started', max_length=50)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=100)),
                ('measure_initiative_weight', models.DecimalField(decimal_places=3, max_digits=3)),
                ('project_phase', models.CharField(choices=[('Contracting', 'Contracting'), ('Requirement', 'Requirement'), ('Approval', 'Approval'), ('Design', 'Design'), ('Development', 'Development'), ('Testing', 'Testing'), ('Deployment', 'Deployment'), ('Live', 'Live')], default='Planning', max_length=50)),
                ('stretch_target_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
