# Generated by Django 6.0 on 2025-12-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='status',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
