# Generated by Django 6.0 on 2026-01-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_status_comment_remove_status_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_phase',
            field=models.CharField(choices=[('Contracting', 'Contracting'), ('Requirement', 'Requirement'), ('Design', 'Design'), ('Development', 'Development'), ('Testing', 'Testing'), ('Deployment', 'Deployment'), ('Live', 'Live')], default='Planning', max_length=50),
        ),
    ]
