# Generated by Django 6.0 on 2026-01-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_project_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='measure_initiative_weight',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
