# Generated by Django 6.0 on 2026-01-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_project_measure_initiative_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_phase',
            field=models.CharField(choices=[('Contracting', 'Contracting'), ('Requirement', 'Requirement'), ('Design', 'Design'), ('Development', 'Development'), ('Testing', 'Testing'), ('Deployment', 'Deployment'), ('Live', 'Live')], default='Requirement', max_length=50),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('Planned', 'Planned'), ('On Track', 'On Track'), ('At Risk', 'At Risk'), ('Delayed', 'Delayed')], default='Not Started', max_length=50),
        ),
    ]
